language: java
before_script:
  - mvn build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}'.$TRAVIS_BUILD_NUMBER -DgenerateBackupPoms=false
after_success:
  - mvn scm:tag -Dtag='${project.version}' -Dmessage='VERSION ${project.version}'
