language: java
before_script:
  - mvn build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}'.$TRAVIS_BUILD_NUMBER -DgenerateBackupPoms=false
after_success:
  - git config --global user.name  "Travis CI"
  - git config --global user.email "builds@travis-ci.com"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - mvn scm:tag -Dtag='${project.version}' -Dmessage='VERSION ${project.version}'
env:
  global:
    secure: EoNoxW3OtReJn0oTBlDU/QQmm67+v+vxn7GLb69GDKubHbQ14kSwvGN5omY1YI2WVm7yT31Ydzn9r00SaeySrrdPY+uyZrq08jNafmqDIo2JsA1Fu/nYUBSznLmXlySB9klBVmiGGa5AdLivOvFYN9Lz9KYlb2MBRYBMOENiqYLu6vPdYEeMyVWH6GcjkXYKXQxXYDVOhGY+/H/b8QfBQTcCsLEC8UIh0wTxrQRZDB72Hnj+1xUiAG6dKfqPxzk7huXBPO+/5OwQJpBQYK1KP1Db3iInfzSwq429m4L8RLtmgf7sPXQSuhuHpYZ3oXuQvAxtl+NZWN3lcQQbmuAFslLdYuQzIhPFGkWPVljvn3TB+Soc2qxEedyJZidrXYMDjs8YM/3Fl55Ard6HxQap2zFIEn+2sFExLXFX5NXLob/+4IgNojVqvV8UAKO8FPPe2oF9R4tHqUte6lVHY06ORzjxnVddcw6QKC3daLRDy5jkzZCLxwGD2x0RwGkuntYv/tqSJccU8l/CO3EvMRPOoo7ctDyvo2f17SNuvIbv1KtmxwKbdtaxVmfTPuIb71g+bNl80AZgNtxB3sqfpozbo1MmFLgGGTtB7WekmuF2LHbnx8vZS+bTvNJEd4rXoe6K6zA/FqxzT9KI9s4364Odi32Fep5lEjWco+JNYjhgyBs=
